import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs-extra';
import archiver from 'archiver';
import { parseOpenAPISpec } from '../lib/parser/openapi-parser';
import { generateTypes } from '../lib/generators/types-generator';
import { generateAPIClient } from '../lib/generators/api-client-generator';
import { generateReduxActions } from '../lib/generators/redux-actions-generator';
import { generateReduxReducers } from '../lib/generators/redux-reducers-generator';
import { generateReduxStore } from '../lib/generators/redux-store-generator';

export async function generateSDKFromBuffer(
  fileBuffer: Buffer,
  fileName: string,
  moduleName: string,
  baseURL?: string
): Promise<Buffer> {
  // Create temporary directory for processing
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'sdk-gen-'));
  const specPath = path.join(tmpDir, fileName);
  const outputDir = path.join(tmpDir, 'output');

  try {
    // Write uploaded file to temp location
    await fs.writeFile(specPath, fileBuffer);
    await fs.ensureDir(outputDir);

    console.log('Parsing OpenAPI spec...');
    const parsedAPI = await parseOpenAPISpec(specPath, baseURL);

    console.log(`Found ${parsedAPI.operations.length} operations`);
    console.log(`Found ${parsedAPI.schemas.length} schemas`);

    // Generate SDK files
    console.log('Generating TypeScript types...');
    await generateTypes(parsedAPI, outputDir);

    console.log('Generating API client...');
    await generateAPIClient(parsedAPI, outputDir, moduleName);

    console.log('Generating Redux actions...');
    await generateReduxActions(parsedAPI, outputDir, moduleName);

    console.log('Generating Redux reducers...');
    await generateReduxReducers(parsedAPI, outputDir, moduleName);

    console.log('Generating Redux store...');
    await generateReduxStore(parsedAPI, outputDir, moduleName);

    console.log('Generating package files...');
    await generatePackageFiles(outputDir, moduleName, parsedAPI.title);

    // Create zip file
    console.log('Creating zip archive...');
    const zipBuffer = await createZipFromDirectory(outputDir);

    return zipBuffer;
  } finally {
    // Clean up temporary directory
    console.log('Cleaning up temporary files...');
    await fs.remove(tmpDir);
  }
}

async function generatePackageFiles(
  outputDir: string,
  moduleName: string,
  apiTitle: string
): Promise<void> {
  // Generate index.ts
  const indexContent = `// Generated by OpenAPI Redux SDK Generator
export * from './types';
export * from './client';
export * from './store';
export * from './actions';
export * from './reducers';
`;

  await fs.writeFile(path.join(outputDir, 'index.ts'), indexContent);

  // Generate package.json
  const packageJson = {
    name: `${moduleName}-sdk`,
    version: '1.0.0',
    description: `Generated SDK for ${apiTitle}`,
    main: 'index.ts',
    peerDependencies: {
      '@reduxjs/toolkit': '^2.0.0',
      redux: '^5.0.0',
      axios: '^1.6.0',
    },
  };

  await fs.writeFile(
    path.join(outputDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  );

  // Generate README
  const readmeContent = `# ${moduleName.toUpperCase()} SDK

Generated Redux-based SDK from OpenAPI specification.

## Installation

\`\`\`bash
npm install axios redux @reduxjs/toolkit
\`\`\`

## Usage

### Configure Store

\`\`\`typescript
import { configureStore } from '@reduxjs/toolkit';
import { ${moduleName}Reducer } from './${moduleName}-sdk';

const store = configureStore({
  reducer: {
    ${moduleName}: ${moduleName}Reducer,
  },
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
\`\`\`

### Use in Components

\`\`\`typescript
import { useDispatch, useSelector } from 'react-redux';
import { fetchData } from './${moduleName}-sdk';

function MyComponent() {
  const dispatch = useDispatch();
  const data = useSelector((state: RootState) => state.${moduleName}.data);

  useEffect(() => {
    dispatch(fetchData());
  }, []);

  return <div>{/* Your component */}</div>;
}
\`\`\`

## Generated by OpenAPI Redux SDK Generator
https://github.com/your-username/openapi-redux-sdk-generator
`;

  await fs.writeFile(path.join(outputDir, 'README.md'), readmeContent);
}

async function createZipFromDirectory(sourceDir: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('data', (chunk) => {
      chunks.push(chunk);
    });

    archive.on('end', () => {
      resolve(Buffer.concat(chunks));
    });

    archive.on('error', (err) => {
      reject(err);
    });

    // Add all files from the directory
    archive.directory(sourceDir, false);
    archive.finalize();
  });
}
