openapi: 3.0.0
info:
  title: Main API with Client Dependencies
  version: 1.0.0
  description: Example of a main OpenAPI spec that depends on client specs

# Spec Dependencies Extension
x-dependencies:
  type: main-with-clients
  consolidationStrategy: main-client-pattern
  clientSpecs:
    - name: UserServiceClient
      source: https://api.example.com/specs/user-service.yaml
      version: 2.1.0
      required: true
      apiDetails:
        baseUrl: https://users.example.com/api/v2
        authentication:
          type: bearer
          location: header
          headerName: Authorization
        rateLimit:
          requestsPerSecond: 100
          requestsPerMinute: 5000
          burstLimit: 150
        timeout: 3000
        retryPolicy:
          maxRetries: 3
          backoffStrategy: exponential
        healthCheck:
          endpoint: /health
          method: GET
          expectedStatus: 200
      endpoints:
        - path: /users/{id}
          method: GET
          operationId: getUserById
          description: Fetch user details by ID
          parameters:
            - name: id
              in: path
              required: true
          expectedResponse:
            statusCode: 200
            schema:
              type: object
              properties:
                id: {type: string}
                name: {type: string}
                email: {type: string}
          estimatedLatency: 150
          cacheable: true
          cachePolicy:
            ttl: 300
            strategy: redis

        - path: /users
          method: POST
          operationId: createUser
          description: Create a new user
          expectedResponse:
            statusCode: 201
          estimatedLatency: 200
          cacheable: false

    - name: OrderServiceClient
      source: https://api.example.com/specs/order-service.yaml
      version: 1.5.3
      required: true
      apiDetails:
        baseUrl: https://orders.example.com/api/v1
        authentication:
          type: apiKey
          location: header
          headerName: X-API-Key
        rateLimit:
          requestsPerSecond: 50
          requestsPerMinute: 2000
          burstLimit: 75
        timeout: 5000
        retryPolicy:
          maxRetries: 2
          backoffStrategy: linear
        healthCheck:
          endpoint: /health
          method: GET
          expectedStatus: 200
      endpoints:
        - path: /orders/{id}
          method: GET
          operationId: getOrderById
          description: Fetch order details
          parameters:
            - name: id
              in: path
              required: true
          expectedResponse:
            statusCode: 200
            schema:
              type: object
              properties:
                orderId: {type: string}
                items: {type: array}
                total: {type: number}
          estimatedLatency: 250
          cacheable: true
          cachePolicy:
            ttl: 60
            strategy: memory

        - path: /orders
          method: POST
          operationId: createOrder
          description: Create a new order
          expectedResponse:
            statusCode: 201
          estimatedLatency: 300
          cacheable: false

    - name: NotificationServiceClient
      source: https://api.example.com/specs/notification-service.yaml
      version: 1.0.0
      required: false
      apiDetails:
        baseUrl: https://notifications.example.com/api/v1
        authentication:
          type: bearer
          location: header
          headerName: Authorization
        rateLimit:
          requestsPerSecond: 20
          requestsPerMinute: 1000
          burstLimit: 30
        timeout: 2000
        retryPolicy:
          maxRetries: 1
          backoffStrategy: fixed
        healthCheck:
          endpoint: /ping
          method: GET
          expectedStatus: 200
      endpoints:
        - path: /notifications/send
          method: POST
          operationId: sendNotification
          description: Send notification to user
          expectedResponse:
            statusCode: 202
          estimatedLatency: 100
          cacheable: false

paths:
  /api/user-orders:
    get:
      summary: Get user with their orders (calls UserServiceClient and OrderServiceClient)
      operationId: getUserOrders
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string

      # Dependency tracking
      x-client-dependencies:
        - clientName: UserServiceClient
          endpoint: GET /users/{id}
          purpose: Fetch user details
        - clientName: OrderServiceClient
          endpoint: GET /orders
          purpose: Fetch user orders

      # API Call Tracking
      x-api-call-tracking:
        enabled: true
        groupBy: [correlationId, apiName]
        description: Track calls to UserServiceClient and OrderServiceClient
        implementation:
          method: logging
          correlationIdHeader: X-Correlation-ID
          propagateToUpstream: true
          logLevel: INFO
          logFormat:
            template: "API_CALL | correlation_id={correlationId} | api_name={apiName} | method={method} | path={path} | status={status} | duration_ms={duration} | upstream_client={upstreamClient}"
            fields: [correlationId, apiName, method, path, status, duration, timestamp, upstreamClient]
          aggregation:
            enabled: true
            aggregateBy: correlationId
            storage: in-memory
            query: SELECT correlation_id, api_name, upstream_client, COUNT(*) as call_count FROM api_logs GROUP BY correlation_id, api_name, upstream_client
          metrics:
            enabled: true
            exportFormat: prometheus
            counters:
              - name: api_calls_total
                description: Total API calls including upstream clients
                labels: [correlation_id, api_name, method, path, status, upstream_client]
              - name: api_calls_per_workflow
                description: API calls grouped by correlation ID and client
                labels: [correlation_id, api_name, upstream_client]
            endpoint: /metrics

      # CO2 Emission Tracking
      x-co2-impact:
        enabled: true
        estimatedGramsPerRequest: 35
        calculationMethod: cloud-carbon-coefficients
        breakdown:
          network: 10
          compute: 15
          storage: 5
          dataTransfer: 5
        upstreamEmissions:
          - client: UserServiceClient
            estimatedGrams: 12
          - client: OrderServiceClient
            estimatedGrams: 18
        mitigationStrategies:
          - caching
          - compression

      responses:
        '200':
          description: User with orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                  orders:
                    type: array
                    items:
                      type: object

  /api/create-order-with-notification:
    post:
      summary: Create order and send notification (calls OrderServiceClient and NotificationServiceClient)
      operationId: createOrderWithNotification

      # Dependency tracking
      x-client-dependencies:
        - clientName: OrderServiceClient
          endpoint: POST /orders
          purpose: Create the order
        - clientName: NotificationServiceClient
          endpoint: POST /notifications/send
          purpose: Send order confirmation
          optional: true

      # API Call Tracking
      x-api-call-tracking:
        enabled: true
        groupBy: [correlationId, apiName]
        implementation:
          method: logging
          correlationIdHeader: X-Correlation-ID
          propagateToUpstream: true
          logLevel: INFO
          logFormat:
            template: "API_CALL | correlation_id={correlationId} | api_name={apiName} | method={method} | path={path} | status={status} | upstream_client={upstreamClient}"
            fields: [correlationId, apiName, method, path, status, timestamp, upstreamClient]
          aggregation:
            enabled: true
            aggregateBy: correlationId
            storage: in-memory
            query: SELECT correlation_id, COUNT(*) as call_count FROM api_logs GROUP BY correlation_id
          metrics:
            enabled: true
            exportFormat: prometheus
            counters:
              - name: api_calls_total
                description: Total API calls
                labels: [correlation_id, api_name, upstream_client]
            endpoint: /metrics

      # CO2 Emission Tracking
      x-co2-impact:
        enabled: true
        estimatedGramsPerRequest: 28
        calculationMethod: cloud-carbon-coefficients
        breakdown:
          network: 8
          compute: 12
          storage: 3
          dataTransfer: 5
        upstreamEmissions:
          - client: OrderServiceClient
            estimatedGrams: 15
          - client: NotificationServiceClient
            estimatedGrams: 8
            optional: true
        mitigationStrategies:
          - async-execution
          - caching

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                items:
                  type: array
                  items:
                    type: object

      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                  notificationSent:
                    type: boolean
