import { GeneratorOptions } from './types';
import { parseOpenAPISpec } from './parser/openapi-parser';
import { generateTypes } from './generators/types-generator';
import { generateAPIClient } from './generators/api-client-generator';
import { generateReduxActions } from './generators/redux-actions-generator';
import { generateReduxReducers } from './generators/redux-reducers-generator';
import { generateReduxStore } from './generators/redux-store-generator';
import { generateRTKQuery } from './generators/rtk-query-generator';
import { generateReactHooks } from './generators/react-hooks-generator';
import { generateSDKUtilities } from './generators/sdk-utilities-generator';
import { generateMonitoringHooks } from './generators/monitoring-hooks-generator';
import { ensureDir } from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import { logger, PerformanceTimer } from './utils/logger';
import { createError, ErrorCode } from './utils/error-codes';

export async function generateSDK(options: GeneratorOptions): Promise<void> {
  const timer = new PerformanceTimer('SDK Generation');
  const { inputSpec, outputDir, moduleName = 'api', baseURL, modernOnly = false, legacyOnly = false } = options;

  try {
    const mode = legacyOnly ? 'legacy' : modernOnly ? 'modern' : 'both';
    logger.info('Starting SDK generation', { inputSpec, outputDir, moduleName, mode });

    console.log(chalk.gray(`Parsing OpenAPI spec: ${inputSpec}`));
    const parsedAPI = await parseOpenAPISpec(inputSpec, baseURL);

    console.log(chalk.gray(`Found ${parsedAPI.operations.length} operations`));
    console.log(chalk.gray(`Found ${parsedAPI.schemas.length} schemas`));
    console.log(chalk.gray(`Generation mode: ${mode}\n`));

    // Ensure output directory exists
    await ensureDir(outputDir);

    // Always generate TypeScript types
    console.log(chalk.blue('📝 Generating TypeScript types...'));
    await generateTypes(parsedAPI, outputDir);

    if (!legacyOnly) {
      // Modern approach - RTK Query + React 19
      console.log(chalk.blue('\n🚀 Modern Stack (RTK Query + React 19)'));

      console.log(chalk.blue('  ├─ RTK Query API...'));
      await generateRTKQuery(parsedAPI, outputDir, moduleName, baseURL);

      console.log(chalk.blue('  ├─ React 19 hooks...'));
      await generateReactHooks(parsedAPI, outputDir, moduleName);

      console.log(chalk.blue('  ├─ SDK utilities...'));
      await generateSDKUtilities(outputDir, moduleName);

      console.log(chalk.blue('  └─ Monitoring hooks...'));
      await generateMonitoringHooks(outputDir, moduleName);
    }

    if (!modernOnly) {
      // Legacy approach - Async thunks + traditional Redux
      console.log(chalk.blue('\n🔌 Legacy Stack (Async Thunks + Redux Toolkit)'));

      console.log(chalk.blue('  ├─ API client...'));
      await generateAPIClient(parsedAPI, outputDir, moduleName);

      console.log(chalk.blue('  ├─ Redux actions (async thunks)...'));
      await generateReduxActions(parsedAPI, outputDir, moduleName);

      console.log(chalk.blue('  ├─ Redux reducers...'));
      await generateReduxReducers(parsedAPI, outputDir, moduleName);

      console.log(chalk.blue('  └─ Store configuration...'));
      await generateReduxStore(parsedAPI, outputDir, moduleName);
    }

    console.log(chalk.blue('\n📦 Generating package files...'));
    await generatePackageFiles(outputDir, moduleName, modernOnly, legacyOnly);

    timer.end(true);
    logger.info('SDK generation completed successfully', {
      outputDir,
      duration: timer.elapsed(),
      mode,
    });
  } catch (error) {
    timer.end(false, error as Error);
    logger.error('SDK generation failed', error as Error);
    throw createError(
      ErrorCode.GENERATION_ERROR,
      `Failed to generate SDK: ${(error as Error).message}`,
      error as Error,
      { inputSpec, outputDir, moduleName }
    );
  }
}

async function generatePackageFiles(
  outputDir: string,
  moduleName: string,
  modernOnly: boolean = false,
  legacyOnly: boolean = false
): Promise<void> {
  const fs = require('fs-extra');

  // Generate index.ts with conditional exports
  let indexContent = `// Generated by openapi-redux-sdk-generator\n`;

  if (!legacyOnly) {
    indexContent += `\n// Modern RTK Query API (Recommended)\n`;
    indexContent += `export * from './api';\n`;
    indexContent += `export * from './types';\n\n`;
    indexContent += `// React 19 Hooks\n`;
    indexContent += `export * from './hooks';\n`;
    indexContent += `export * from './monitoring-hooks';\n\n`;
    indexContent += `// Utilities\n`;
    indexContent += `export * from './error-handling';\n`;
    indexContent += `export * from './monitoring';\n`;
    indexContent += `export * from './logger';\n`;
  }

  if (!modernOnly) {
    if (!legacyOnly) {
      indexContent += `\n// Legacy exports (for backwards compatibility)\n`;
    } else {
      indexContent += `\n// Legacy Redux with Async Thunks\n`;
    }
    indexContent += `export * from './client';\n`;
    indexContent += `export * from './store';\n`;
    indexContent += `export * from './actions';\n`;
    indexContent += `export * from './reducers';\n`;
    if (legacyOnly) {
      indexContent += `export * from './types';\n`;
    }
  }

  await fs.writeFile(path.join(outputDir, 'index.ts'), indexContent);

  // Generate package.json
  const packageJson = {
    name: `${moduleName}-sdk`,
    version: '1.0.0',
    description: `Generated SDK for ${moduleName} with React 19 and RTK Query support`,
    main: 'index.ts',
    types: 'index.ts',
    peerDependencies: {
      '@reduxjs/toolkit': '^2.0.0',
      'react': '^19.0.0',
      'react-redux': '^9.0.0'
    },
    devDependencies: {
      'typescript': '^5.0.0'
    }
  };

  await fs.writeFile(
    path.join(outputDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  );

  // Generate README
  const readmeContent = `# ${moduleName.toUpperCase()} SDK

Modern Redux Toolkit Query SDK generated from OpenAPI specification.

Built with:
- **Redux Toolkit Query** for efficient data fetching
- **React 19** features (useOptimistic, use, useTransition)
- **TypeScript** for full type safety
- **Comprehensive error handling** and retry logic
- **Performance monitoring** and metrics
- **Structured logging** for debugging

## Installation

\`\`\`bash
npm install @reduxjs/toolkit react-redux react@19
\`\`\`

## Quick Start

### 1. Configure Store

\`\`\`typescript
import { configureStore } from '@reduxjs/toolkit';
import { ${moduleName}Api, ${moduleName}ApiReducer, ${moduleName}ApiMiddleware } from './${moduleName}-sdk';

export const store = configureStore({
  reducer: {
    [${moduleName}Api.reducerPath]: ${moduleName}ApiReducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(${moduleName}ApiMiddleware),
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
\`\`\`

### 2. Wrap App with Provider

\`\`\`typescript
import { Provider } from 'react-redux';
import { store } from './store';

function App() {
  return (
    <Provider store={store}>
      <YourApp />
    </Provider>
  );
}
\`\`\`

### 3. Use RTK Query Hooks

\`\`\`typescript
import { useGetUsersQuery, useCreateUserMutation } from './${moduleName}-sdk';

function UserList() {
  // Automatic caching, refetching, and loading states
  const { data, error, isLoading } = useGetUsersQuery({ limit: 10 });

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error: {error.message}</div>;

  return (
    <ul>
      {data?.map(user => <li key={user.id}>{user.name}</li>)}
    </ul>
  );
}

function CreateUser() {
  const [createUser, { isLoading, error }] = useCreateUserMutation();

  const handleSubmit = async (formData) => {
    await createUser(formData).unwrap();
  };

  return <form onSubmit={handleSubmit}>...</form>;
}
\`\`\`

## React 19 Features

### Optimistic Updates

\`\`\`typescript
import { useOptimisticMutation } from './${moduleName}-sdk';

function OptimisticUpdate() {
  const { mutate, isPending } = useOptimisticMutation(
    async (data) => createUser(data).unwrap(),
    {
      getOptimisticData: (data) => ({ id: 'temp', ...data }),
      onSuccess: () => console.log('Success!'),
    }
  );

  return <button onClick={() => mutate({ name: 'John' })}>Create</button>;
}
\`\`\`

### Suspense Integration

\`\`\`typescript
import { Suspense } from 'react';
import { useSuspenseQuery } from './${moduleName}-sdk';

function DataComponent() {
  const data = useSuspenseQuery(() => fetchUser('123'), ['123']);
  return <div>{data.name}</div>;
}

function App() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <DataComponent />
    </Suspense>
  );
}
\`\`\`

## Error Handling

\`\`\`typescript
import { ApiError, retryWithBackoff } from './${moduleName}-sdk';

try {
  const result = await retryWithBackoff(
    () => someApiCall(),
    { maxRetries: 3 }
  );
} catch (error) {
  if (error instanceof ApiError) {
    console.log('Error code:', error.code);
    console.log('Status:', error.status);
  }
}
\`\`\`

## Monitoring

\`\`\`typescript
import { useApiMetrics, useNetworkStatus } from './${moduleName}-sdk';

function MonitoringDashboard() {
  const metrics = useApiMetrics();
  const isOnline = useNetworkStatus();

  return (
    <div>
      <p>Network: {isOnline ? 'Online' : 'Offline'}</p>
      <p>Total Requests: {metrics.totalRequests}</p>
      <p>Success Rate: {100 - metrics.errorRate}%</p>
      <p>Avg Response Time: {metrics.averageResponseTime}ms</p>
    </div>
  );
}
\`\`\`

## Logging

\`\`\`typescript
import { logger, LogLevel } from './${moduleName}-sdk';

// Configure logging
logger.setLevel(LogLevel.DEBUG);
logger.setEnabled(true);

// Use in your code
logger.info('User logged in', { userId: '123' });
logger.error('API call failed', error);
\`\`\`

## Generated Files

### Modern (RTK Query)
- \`api.ts\` - RTK Query API with all endpoints
- \`hooks.ts\` - React 19 custom hooks
- \`monitoring-hooks.ts\` - Performance monitoring hooks

### Utilities
- \`error-handling.ts\` - Error codes and handlers
- \`monitoring.ts\` - Metrics collection
- \`logger.ts\` - Client-side logging

### Types
- \`types.ts\` - TypeScript definitions from OpenAPI

### Legacy (Optional)
- \`client.ts\` - Axios-based API client
- \`actions.ts\` - Redux async thunks
- \`reducers.ts\` - Redux slices
- \`store.ts\` - Store helpers

## Best Practices

1. **Use RTK Query hooks** for all data fetching
2. **Enable monitoring** in development for debugging
3. **Implement error boundaries** for graceful error handling
4. **Use optimistic updates** for better UX
5. **Leverage React 19 Suspense** for loading states
6. **Configure retry logic** for transient failures
7. **Monitor API metrics** in production

## Documentation

For more examples, see the \`examples/\` directory in the generator repository.
`;

  await fs.writeFile(path.join(outputDir, 'README.md'), readmeContent);
}
